### ISSUE TITLE
luci 页面上啥都是加载中

### ISSUE THREAD

**Issue by shellus** [crazygit/openwrt-x86-64#4]
```
#Dockerfile
FROM crazygit/openwrt-x86-64

EXPOSE 80

USER root

CMD /sbin/init

```
```
#docker-compose.yml
version: "2"
services:
  lede:
    build: ./build
    ports:
      - "8080:80"
    restart: unless-stopped
```

```
docker-compose logs
Attaching to lede_lede_1
lede_1  | ip: RTNETLINK answers: Operation not permitted
lede_1  | Press the [f] key and hit [enter] to enter failsafe mode
lede_1  | Press the [1], [2], [3] or [4] key and hit [enter] to select the debug level
lede_1  | ip: can't send flush request: Operation not permitted
lede_1  | ip: SIOCSIFFLAGS: Operation not permitted

```

访问IP:8080 可以进入luci页面，但是无论是首页的状态页面，还是网络-接口页面，都是无限加载中“Loading view…”，在一分钟左右变成“Error
XHR request timed out”

个别页面可以打开，例如“系统-管理权”，而且交互也正常，可以成功修改密码
